spring.application.name=jobtracker
server.port=${PORT:8080}
server.error.include-message=always
# Online MongoDB Atlas URI
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://jobtracker_user:abcd123@cluster0.8q7mge3.mongodb.net/jobtracker?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://jobtracker_user:abcd123@cluster0.8q7mge3.mongodb.net/jobtracker?retryWrites=true&w=majority&appName=Cluster0}

jwt.secret=${JWT_SECRET:my-super-secret-key-for-job-tracker-application-123456}
jwt.expiration=86400000

